//@version=6
//Basic Hull Ma Pack tinkered by InSilico 
indicator('Hull Suite by InSilico', overlay = true)

//INPUT
src = input(close, title = 'Source')
modeSwitch = input.string('Hma', title = 'Hull Variation', options = ['Hma', 'Thma', 'Ehma'])
length = input(55, title = 'Length(180-200 for floating S/R , 55 for swing entry)')
lengthMult = input(1.0, title = 'Length multiplier (Used to view higher timeframes with straight band)')

useHtf = input(false, title = 'Show Hull MA from X timeframe? (good for scalping)')
htf = input.timeframe('240', title = 'Higher timeframe')

switchColor = input(true, 'Color Hull according to trend?')
candleCol = input(false, title = 'Color candles based on Hull\'s Trend?')
visualSwitch = input(true, title = 'Show as a Band?')
thicknesSwitch = input(1, title = 'Line Thickness')
transpSwitch = input.int(40, title = 'Band Transparency', step = 5)

//FUNCTIONS
//HMA
HMA(_src, _length) =>
    ta.wma(2 * ta.wma(_src, _length / 2) - ta.wma(_src, _length), math.round(math.sqrt(_length)))
    //EHMA    
EHMA(_src, _length) =>
    ta.ema(2 * ta.ema(_src, _length / 2) - ta.ema(_src, _length), math.round(math.sqrt(_length)))
    //THMA    
THMA(_src, _length) =>
    ta.wma(ta.wma(_src, _length / 3) * 3 - ta.wma(_src, _length / 2) - ta.wma(_src, _length), _length)

//SWITCH
Mode(modeSwitch, src, len) =>
    modeSwitch == 'Hma' ? HMA(src, len) : modeSwitch == 'Ehma' ? EHMA(src, len) : modeSwitch == 'Thma' ? THMA(src, len / 2) : na

//OUT
_hull = Mode(modeSwitch, src, int(length * lengthMult))
HULL = useHtf ? request.security(syminfo.ticker, htf, _hull) : _hull
MHULL = HULL[0]
SHULL = HULL[2]

//COLOR
hullColor = switchColor ? HULL > HULL[2] ? #00ff00 : #ff0000 : #ff9800

//PLOT
///< Frame
Fi1 = plot(MHULL, title = 'MHULL', color = hullColor, linewidth = math.max(1, thicknesSwitch))
Fi2 = plot(visualSwitch ? SHULL : na, title = 'SHULL', color = hullColor, linewidth = math.max(1, thicknesSwitch))
alertcondition(ta.crossover(MHULL, SHULL), title = 'Hull trending up.', message = 'Hull trending up.')
alertcondition(ta.crossover(SHULL, MHULL), title = 'Hull trending down.', message = 'Hull trending down.')
///< Ending Filler
fill(Fi1, Fi2, title = 'Band Filler', color = hullColor)
///BARCOLOR
barcolor(color = candleCol ? switchColor ? hullColor : na : na)
