//@version=6
indicator('Win-Loss Streak Plotter', overlay = false)

//INPUT//


src = input.source(open, title = 'Source')
f_ma = input.source(open, title = 'Fast Moving Average')
s_ma = input.source(open, title = 'Slow Moving Average')

t_cross = input.int(102, title = 'Total Crosses to Analyze', minval = 1)
cpr = input.int(34, title = 'Crosses per Row', minval = 1)

//CALCULATION

p_cross = ta.crossover(f_ma, s_ma)
n_cross = ta.crossunder(f_ma, s_ma)

//CALCULATION

var float last_cross_price = na
var bool is_positive_cross = false

var int total_crosses = 0
var int wins = 0

var results = array.new_int()


if p_cross or n_cross
    if not na(last_cross_price)

        price_change = (src - last_cross_price) / last_cross_price * 100

        win = is_positive_cross ? price_change > 0 : price_change < 0
        total_crosses := total_crosses + 1
        if win
            wins := wins + 1
            wins

        array.push(results, win ? 1 : -1)

        if array.size(results) > t_cross
            array.shift(results)

    last_cross_price := src

    is_positive_cross := p_cross
    is_positive_cross


ma_win_rate = total_crosses > 0 ? math.round(wins / total_crosses * 100, 2) : na


rows_count = int(math.ceil(t_cross / cpr))

//PLOT//

var table result_table = table.new(position.bottom_right, cpr, rows_count, border_width = 1)


for i = 0 to t_cross - 1 by 1
    r = int(i / cpr)
    c = i % cpr
    result_text = str.tostring(i + 1)
    cell_color = color.gray
    if i < array.size(results)
        cross_result = array.get(results, i)
        result_text := str.tostring(i + 1)
        cell_color := cross_result == 1 ? color.green : color.red
        cell_color
    table.cell(result_table, c, r, result_text, text_color = color.white, bgcolor = cell_color, text_size = size.auto)

var table winrate = table.new(position.middle_left, 1, 1, bgcolor = color.green)

table.cell(winrate, 0, 0, str.tostring(ma_win_rate), text_color = color.white, text_size = size.large)
